module Enumerable[unchecked out Elem] : _Each[Elem]
  def collect: [T]() { (Elem item) -> T } -> Array[T]

  alias map collect

  def each_with_index: () { (Elem item, Integer index) -> void } -> self
end
