class Integer < Object
  def []: (Integer) -> Integer

  def +@: () -> Integer

  def -@: () -> Integer

  def +: (Integer) -> Integer
       | (Float) -> Float

  def -: (Integer) -> Integer
       | (Float) -> Float

  def *: (Integer) -> Integer
       | (Float) -> Float

  def /: (Integer) -> Integer
       | (Float) -> Float

  def **: (Integer) -> Integer
        | (Float) -> Float

  def %: (Integer) -> Integer

  def &: (Integer) -> Integer

  def |: (Integer) -> Integer

  def ^: (Integer) -> Integer

  def ~: () -> Integer

  def <<: (Integer) -> Integer

  def >>: (Integer) -> Integer

  def <: (Integer | Float other) -> bool

  def <=: (Integer | Float other) -> bool

  def >: (Integer | Float other) -> bool

  def >=: (Integer | Float other) -> bool

  def abs: () -> Integer

  def clamp: (Integer min, Integer max) -> Integer
           | (Integer | Float min, Integer | Float max) -> (Integer | Float)

  def to_i: () -> Integer

  def to_f: () -> Float

  # TODO: String
  # def chr: () -> String

  # TODO: String
  # def inspect: () -> String
  # def self.inspect: () -> String
  #
  # alias to_s inspect
  # alias self.to_s self.inspect

  def times: () { (Integer i) -> void } -> self

  def upto: (Integer max) { (Integer i) -> void } -> self

  def downto: (Integer min) { (Integer i) -> void } -> self
end
